import { Inter } from 'next/font/google';
import './globals.css';
import RTKProvider from './qurey/Provider'; // Assuming this path is correct
import 'react-toastify/dist/ReactToastify.css';
import ProtectedRoute from './route/ProtectedRoute';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RTKProvider>
          {children}
        </RTKProvider>
      </body>
    </html>
  );
}
